[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.3.1"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.19.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  version = "1.8.5"
