apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: accounts
    tier: db
  ports:
    - port: 5432
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: accounts
      tier: db
  template:
    metadata:
      labels:
        app: accounts
        tier: db
    spec:
      containers:
        - image: postgres:11.2-alpine
          name: postgres
